### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by lavie666** [lavie666/furima-35232#9]
自身のフリマアプリのURL↓
https://furima-35232.herokuapp.com/

Basic認証のIDとパスワード↓
ID:hamada
パスワード:1234

出品者用のメールアドレスとパスワード↓
email:hama@com
パスワード:aaa111

購入者用のメールアドレスとパスワード↓
email:poko@com
パスワード:aaa111

ご確認よろしくお願いいたします！

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **商品購入ページでは、一覧や詳細ページで選択した商品の情報（商品名・商品画像・販売金額・配送料負担）が、見本アプリと同様の形で出力されるようにしましょう**
商品名が正しく表示されていません。
<img width="734" alt="スクリーンショット 2021-04-27 14 47 19" src="https://user-images.githubusercontent.com/62644781/116191736-cd229d80-a767-11eb-8315-ef454a2405fa.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by lavie666** [comment]
修正いたしました！確認よろしくお願いいたします！

**Comment by takumi0530** [comment]
@lavie666 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/116194048-41ab0b80-a76b-11eb-952c-d58c465b7d60.png)
